package com.jwebcoder.grocerymain.common.dto;


import com.jwebcoder.grocerymain.common.entity.PersonalInfo;

import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

public class SystemUserDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.USER_NAME
     *
     * @mbggenerated
     */
    @Column(name = "USER_NAME")
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.TYPE
     *
     * @mbggenerated
     */
    @Column(name = "TYPE")
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.EMAIL
     *
     * @mbggenerated
     */
    @Column(name = "EMAIL")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.CREATE_DATETIME
     *
     * @mbggenerated
     */
    @Column(name = "CREATE_DATETIME")
    private String createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.LAST_LOGIN_DATETIME
     *
     * @mbggenerated
     */
    @Column(name = "LAST_LOGIN_DATETIME")
    private String lastLoginDatetime;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name="id",referencedColumnName="id")
    private PersonalInfo personalInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.CUSTOM1
     *
     * @mbggenerated
     */
    @Column(name = "CUSTOM1")
    private String custom1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.CUSTOM2
     *
     * @mbggenerated
     */
    @Column(name = "CUSTOM2")
    private String custom2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.CUSTOM3
     *
     * @mbggenerated
     */
    @Column(name = "CUSTOM3")
    private String custom3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.CUSTOM4
     *
     * @mbggenerated
     */
    @Column(name = "CUSTOM4")
    private String custom4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.CUSTOM5
     *
     * @mbggenerated
     */
    @Column(name = "CUSTOM5")
    private String custom5;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getCreateDatetime() {
        return createDatetime;
    }

    public void setCreateDatetime(String createDatetime) {
        this.createDatetime = createDatetime;
    }

    public String getLastLoginDatetime() {
        return lastLoginDatetime;
    }

    public void setLastLoginDatetime(String lastLoginDatetime) {
        this.lastLoginDatetime = lastLoginDatetime;
    }

    public PersonalInfo getPersonalInfo() {
        return personalInfo;
    }

    public void setPersonalInfo(PersonalInfo personalInfo) {
        this.personalInfo = personalInfo;
    }

    public String getCustom1() {
        return custom1;
    }

    public void setCustom1(String custom1) {
        this.custom1 = custom1;
    }

    public String getCustom2() {
        return custom2;
    }

    public void setCustom2(String custom2) {
        this.custom2 = custom2;
    }

    public String getCustom3() {
        return custom3;
    }

    public void setCustom3(String custom3) {
        this.custom3 = custom3;
    }

    public String getCustom4() {
        return custom4;
    }

    public void setCustom4(String custom4) {
        this.custom4 = custom4;
    }

    public String getCustom5() {
        return custom5;
    }

    public void setCustom5(String custom5) {
        this.custom5 = custom5;
    }
}