package com.jwebcoder.grocerymain.photography.entity;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

@Entity
@Table(name = "PHOTOGRAPHY_PHOTO")
public class PhotographyPhoto {

    @Id
    @Column(name = "ID")
    @GenericGenerator(name = "uuid", strategy = "uuid")
    @GeneratedValue(generator = "uuid")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.VERSION
     *
     * @mbggenerated
     */
    @Column(name = "VERSION")
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_PHOTO.TYPE
     *
     * @mbggenerated
     */
    @Column(name = "TYPE")
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_PHOTO.COMMENTS
     *
     * @mbggenerated
     */
    @Column(name = "PHOTO_ABSOLUTE_PATH", insertable = false, updatable = false)
    private String path;

    @Column(name = "COMMENTS", insertable = false, updatable = false)
    private String desc;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }
}