package com.jwebcoder.grocerymain.photography.entity;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

@Entity
@Table(name = "PHOTOGRAPHY_DETAIL")
public class PhotographyDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.ID
     *
     * @mbggenerated
     */
    @Id
    @Column(name = "ID")
    @GenericGenerator(name = "uuid", strategy = "uuid")
    @GeneratedValue(generator = "uuid")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER.VERSION
     *
     * @mbggenerated
     */
    @Column(name = "VERSION")
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_DETAIL.THEME
     *
     * @mbggenerated
     */
    @Column(name = "THEME")
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_DETAIL.COMMENTS
     *
     * @mbggenerated
     */
    @Column(name = "COMMENTS")
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_DETAIL.PHOTO_REF_ID
     *
     * @mbggenerated
     */
    @Column(name = "PHOTO_REF_ID", insertable = false, updatable = false)
    private String photoRefId;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PHOTO_REF_ID", referencedColumnName = "ID")
    private PhotographyPhoto photographyPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHOTOGRAPHY_DETAIL.CREATE_DATETIME
     *
     * @mbggenerated
     */
    @Column(name = "CREATE_DATETIME")
    private String createDatetime;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getTheme() {
        return theme;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getPhotoRefId() {
        return photoRefId;
    }

    public void setPhotoRefId(String photoRefId) {
        this.photoRefId = photoRefId;
    }

    public PhotographyPhoto getPhotographyPhoto() {
        return photographyPhoto;
    }

    public void setPhotographyPhoto(PhotographyPhoto photographyPhoto) {
        this.photographyPhoto = photographyPhoto;
    }

    public String getCreateDatetime() {
        return createDatetime;
    }

    public void setCreateDatetime(String createDatetime) {
        this.createDatetime = createDatetime;
    }
}